#!/bin/bash

groupIdDefault=com.mycompany
versionDefault=0.0.1-SNAPSHOT
javaVersionDefault=21

read -p "Project groupId (${groupIdDefault}): " groupId
read -p "Project artifactId: " artifactId
read -p "Project version (${versionDefault}): " version
read -p "Java version (${javaVersionDefault}): " javaVersion

mvn --batch-mode \
    -Pjava-maven-quickstart \
    -DarchetypeGroupId=org.grumpyf0x48 \
    -DarchetypeArtifactId=java-maven-quickstart \
    -DarchetypeVersion=0.1-SNAPSHOT \
    -DgroupId="${groupId:-${groupIdDefault}}" \
    -DartifactId="${artifactId}" \
    -Dversion="${version:-${versionDefault}}" \
    -DjavaVersion="${javaVersion:-${javaVersionDefault}}" \
     archetype:generate
