#!/bin/bash

groupIdDefault=com.mycompany
versionDefault=0.01-SNAPSHOT
javaVersionDefault=1.8

read -p "Project groupId (${groupIdDefault}): " groupId
read -p "Project artifactId: " artifactId
read -p "Project version (${versionDefault}): " version
read -p "Java version (${javaVersionDefault}): " javaVersion

mvn --batch-mode \
    -DarchetypeGroupId=org.grumpyf0x48 \
    -DarchetypeArtifactId=java-minimal-quickstart \
    -DarchetypeVersion=1.0.0 \
    -DgroupId="${groupId:-${groupIdDefault}}" \
    -DartifactId="${artifactId}" \
    -Dversion="${version:-${versionDefault}}" \
    -DjavaVersion="${javaVersion:-${javaVersionDefault}}" \
     archetype:generate
